stages:
  - lint
  - build
  - test
  - push
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY/tol/sts/build-base:1.0.0
  DIND_IMAGE: $CI_REGISTRY/isg/gitlab-ci-docker-docker
  BUILD_IMAGE: $CI_REGISTRY/isg/gitlab-ci-docker-docker

lint:
  tags:
    - autoscale
  image: python:3.7
  stage: lint
  script:
    - pip install flake8
    - flake8 submissions-api/swagger_server/

.job_template: &start_docker
  tags:
   - openstack-autoscale-theta-docker-in-docker
  retry: 2
  before_script:
   - mkdir -p /etc/docker
   - echo '{"bip":"192.168.5.3/24","registry-mirrors":["https://docker-hub-mirror.internal.sanger.ac.uk:5000"],"default-address-pools":[{"base":"192.168.4.0/16","size":24}]}' > /etc/docker/daemon.json
   - dockerd > /var/log/dockerd.log 2>&1 &
   - sleep 10
   - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY


.build-template: &build-template
  <<: *start_docker
  image: $BUILD_IMAGE
  variables:
    DOCKER_TLS_CERTDIR: ''
  stage: build
  script:
    - docker pull $CI_REGISTRY_IMAGE/$NAME:$CI_COMMIT_REF_SLUG || true
    - docker build --pull --cache-from $CI_REGISTRY_IMAGE/$NAME:$CI_COMMIT_REF_SLUG -t $CI_REGISTRY_IMAGE/$NAME:$CI_COMMIT_SHA -f $DOCKERFILE $PART
    - docker push $CI_REGISTRY_IMAGE/$NAME:$CI_COMMIT_SHA

build-api:
  <<: *build-template
  variables:
    PART: "submissions-api"
    DOCKERFILE: "submissions-api/Dockerfile"
    NAME: "submissions-api"

build-ui:
  <<: *build-template
  variables:
    PART: "submissions-ui"
    DOCKERFILE: 'submissions-ui/Dockerfile'
    NAME: "submissions-ui"

build-ui-test:
  <<: *build-template
  variables:
    PART: "submissions-ui"
    DOCKERFILE: 'submissions-ui/Dockerfile.dev'
    NAME: "submissions-ui-test"

test-api:
  <<: *start_docker
  image: $BUILD_IMAGE
  stage: test
  script:
    - docker swarm init
    - docker stack deploy --with-registry-auth -c docker-compose.gitlab.yml -c docker-compose.gitlab-test.yml submissions
    - sleep 60
    - docker service ls
    - docker ps
    - docker service logs submissions_submissions-db
    - docker exec $(docker ps -q -f name="submissions_submissions-api") bash -c "pip3 install tox; tox"

test-ui:
  <<: *start_docker
  image: $BUILD_IMAGE
  stage: test
  script:
    - docker run -e CI=true $CI_REGISTRY_IMAGE/submissions-ui-test:$CI_COMMIT_SHA yarn test

.push-template: &push-template
  <<: *start_docker
  image: $BUILD_IMAGE
  stage: push
  variables:
    GIT_STRATEGY: none
  script:
    - docker pull $CI_REGISTRY_IMAGE/$NAME:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE/$NAME:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/$NAME:$CI_COMMIT_REF_SLUG
    - docker push $CI_REGISTRY_IMAGE/$NAME:$CI_COMMIT_REF_SLUG

push-api:
  <<: *push-template
  variables:
    GIT_STRATEGY: none
    NAME: submissions-api

push-ui:
  <<: *push-template
  variables:
    GIT_STRATEGY: none
    NAME: submissions-ui

push-ui-test:
  <<: *push-template
  variables:
    GIT_STRATEGY: none
    NAME: submissions-ui-test

.deploy-template: &deploy-template
  <<: *start_docker
  image: $BUILD_IMAGE
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - docker stack rm submissions
    - sleep 20
    - docker stack deploy --with-registry-auth -c docker-compose.gitlab.yml -c docker-compose.gitlab-logging.yml submissions

deploy-staging:
  <<: *deploy-template
  environment:
    name: staging
    url: https://submissions-staging.tol.sanger.ac.uk
  variables:
    DOCKER_HOST: "ssh://ubuntu@172.27.22.28"
  only:
    - staging

deploy-production:
  <<: *deploy-template
  environment:
    name: production
    url: https://submissions.tol.sanger.ac.uk/
  variables:
    DOCKER_HOST: "ssh://ubuntu@172.27.22.202"
  only:
    - master
  when: manual
