# SPDX-FileCopyrightText: 2021 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

# This file assumes that staging and master commits will have previously been built and
# tested in the dev branch (deployment will fail otherwise)
#
# test-integration will deploy a test instance and run tests. It uses a resource_group
# to ensure that other pipelines cannot run this task at the same time

include:
  - project: 'tol/tol-core'
    ref: main
    file: '/gitlab/main.yml'

stages:
  - lint
  - build
  - unit test
  - deploy

build-api:
  extends: .build-template
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ''
    PART: "submissions-api"
    DOCKERFILE: "submissions-api/Dockerfile"
    NAME: "submissions-api"

build-ui:
  extends: .build-template
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ''
    PART: "submissions-ui"
    DOCKERFILE: 'submissions-ui/Dockerfile'
    NAME: "submissions-ui"

test-migrations:
  extends: .test-migrations
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ''
    GIT_STRATEGY: none
    NAME: submissions-api

deploy-qa:
  extends: .auto-deploy
  environment:
    name: qa
    url: http://submissions-qa.tol.sanger.ac.uk
  only:
    - qa

deploy-staging:
  extends: .auto-deploy
  environment:
    name: staging
    url: https://submissions-staging.tol.sanger.ac.uk
  only:
    - staging

deploy-production:
  extends: .auto-deploy
  environment:
    name: production
    url: https://submissions.tol.sanger.ac.uk/
  only:
    - production
  when: manual
