# SPDX-FileCopyrightText: 2021 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

# This is used for staging and production deployment in CI/CD
version: '3'
services: 
  submissions-api:
    image: $CI_REGISTRY_IMAGE/submissions-api:$CI_COMMIT_SHA
    networks:
      - submissions
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - ${ENV_FILE}
    environment:
      - ENVIRONMENT=${CI_ENVIRONMENT_NAME}
    ports: 
      - 5000:80
  submissions-ui:
    image: $CI_REGISTRY_IMAGE/submissions-ui:$CI_COMMIT_SHA
    networks:
      - submissions
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - ${ENV_FILE}
#    entrypoint: /bin/sh -c "envsubst "\\$$STS_API_LOCATION" < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && cat /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    ports: 
      - 8000:80
    volumes:
      - schema-html:/var/www/schema
  submissions-dbutils:
    image: $CI_REGISTRY/tol/tol-core/dbutils:1.0.2
    networks:
      - submissions
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - ${ENV_FILE}
  submissions-schema:
    image: $CI_REGISTRY/tol/tol-core/schemaspy:0.2.0
    networks:
      - submissions
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    env_file:
      - ${ENV_FILE}
    volumes:
      - schema-html:/output
networks:
    submissions:
      driver: overlay
volumes:
  schema-html:
