# SPDX-FileCopyrightText: 2021 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

# This is used for local development only
version: '3.1'

services:
  submissions-db:
    image: postgres:11
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5434:5432

  submissions-api:
    build:
      context: submissions-api/.
      dockerfile: Dockerfile.dev
    image: submissions-api
    # force amd64 emulation on M1 Macs
    platform: linux/amd64
    environment:
      - DB_URI
      - ELIXIR_CLIENT_ID
      - ELIXIR_CLIENT_SECRET
      - ELIXIR_REDIRECT_URI
      - ELIXIR_JWK
      - TOLID_URL
      - TOLID_API_KEY
      - ENA_URL
      - ENA_USERNAME
      - ENA_PASSWORD
      - ENA_CONTACT_NAME
      - ENA_CONTACT_EMAIL
      - STS_URL
      - STS_API_KEY
      - NIH_API_KEY
      - ENVIRONMENT
    ports:
      - 8081:80
    volumes:
      - './submissions-api/app/main:/app/main'

  submissions-ui:
    build:
      context: submissions-ui/.
      dockerfile: Dockerfile.dev
    # force amd64 on M1 MacOS
    platform: linux/amd64
    image: submissions-ui
    stdin_open: true
    environment:
      - NODE_ENV=development
    ports:
      - 3003:3000
    volumes:
      - './submissions-ui/app:/usr/src/app'
      - '/usr/src/app/node_modules'

  submissions-ui-test:
    image: submissions-ui
    command: yarn test
    stdin_open: true
    environment:
      - NODE_ENV=development
    volumes:
      - './submissions-ui/app:/usr/src/app'
      - '/usr/src/app/node_modules'

  submissions-alembic:
    image: submissions-api
    container_name: submissions-alembic
    restart: always
    environment:
      - DB_URI
      - DB_LEGACY_TABLES
    entrypoint: /migrations/alembic/docker-entrypoint.sh
    working_dir: /migrations
    volumes:
      - ./submissions-api/migrations/alembic/versions:/migrations/alembic/versions

  submissions-dbutils:
    image: gitlab-registry.internal.sanger.ac.uk/tol/tol-core/dbutils:1.0.2
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
      - BACKUP_S3_URI
      - BACKUP_S3_ACCESS_KEY
      - BACKUP_S3_SECRET_KEY
      - BACKUP_S3_BUCKET
      - BACKUP_S3_SECURE
      - BACKUP_SCHEDULE
      - RESTORE_FILE_PREFIX
      - FLASK_ENV

  submissions-python-db:
    image: postgres:12
    environment:
      - POSTGRES_USER=test-user
      - POSTGRES_PASSWORD=test-password
      - POSTGRES_DB=test-db
  
  submissions-python-unit-test:
    build:
      context: submissions-api
      dockerfile: Dockerfile.test
    command: pytest -v unit

  submissions-python-system-test:
    build:
      context: submissions-api
      dockerfile: Dockerfile.test
    command: pytest -v system
    environment:
      - DB_URI=postgresql://test-user:test-password@submissions-python-db:5432/test-db
      - API_PATH
      - API_TOKEN
    depends_on:
      - submissions-python-db
