openapi: 3.0.0
info:
  title: Tree of Life Submissions API
  description: API for ToL Submissions
  contact:
    email: tol-platforms@sanger.ac.uk
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://0.0.0.0:8081/api/v1
tags:
- name: submitters
  description: Submitting
- name: auth
  description: Authorisation
paths:
  /manifests:
    post:
      security:
        - ApiKeyAuth: []
      tags:
      - submitters
      summary: Submit a JSON manifest
      description: |
        Submits an manifest in JSON format
      operationId: submit_manifest_json
      requestBody:
        description: Manifest to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Manifest'
      responses:
        "200":
          description: manifest created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Manifest'
                x-content-type: application/json
        "400":
          description: invalid input, object invalid, or item already exists
        "403":
          description: user not authorised to use this function
      x-openapi-router-controller: swagger_server.controllers.submitters_controller
  /manifests/excel:
    post:
      security:
        - ApiKeyAuth: []
      tags:
      - users
      summary: Submit an excel manifest
      description: |
        Submits an excel manifest and offers option to download manifest with accession numbers filled in
      operationId: submit_manifest
      parameters:
        - name: sampleColumnHeading
          in: query
          description: the column heading of the column containing the sample id
          required: false
          style: form
          explode: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              x-body-name: excelFile
              type: object
              properties:
                excelFile:
                  type: string
                  format: binary
              required:
                - excelFile
      responses:
        "200":
          description: An Excel file, with the accession numbers filled in
          content:
            application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
              schema:
                type: string
                format: binary
        "400":
          description: manifest has not submitted
      x-openapi-router-controller: swagger_server.controllers.submitters_controller
  /auth/login:
    get:
      tags:
      - auth
      summary: Get the Elixir login URL
      description: |
        Get the URL for logging in to Elixir
      operationId: login
      responses:
        "200":
          description: details of Elixir login URL
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    loginUrl:
                      type: string
        "400":
          description: bad input parameter
      x-openapi-router-controller: swagger_server.controllers.auth_controller
  /auth/token:
    post:
      tags:
      - auth
      summary: Get an Elixir authorisation token
      description: |
        Get the URL for logging in to Elixir
      operationId: get_token_from_callback
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                state:
                  type: string
      responses:
        "200":
          description: authorisation token from Elixir
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    token:
                      type: string
        "400":
          description: bad input parameter
      x-openapi-router-controller: swagger_server.controllers.auth_controller
  /auth/profile:
    post:
      tags:
      - auth
      summary: Get a user profile
      description: |
        Get the URL for logging in to Elixir
      operationId: create_user_profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
      responses:
        "200":
          description: user
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/User'
        "400":
          description: bad input parameter
      x-openapi-router-controller: swagger_server.controllers.auth_controller
components:
  schemas:
    Manifest:
      required:
        - manifestId
        - samples
      type: object
      properties:
        manifestId:
          type: string
          example: manifest12345
        samples:
          type: array
          items:
            $ref: '#/components/schemas/Sample'
      example:
        manifestId: manfest12345
        samples:
          - sampleId: sample1
            taxonomyId: 6344
            specimenId: SAN000100
    Sample:
      required:
        - sampleId
        - taxonomyId
        - specimenId
      type: object
      properties:
        sampleId:
          type: string
          example: sample1
        taxonomyId:
          type: integer
          example: 6344
        scientificName:
          type: string
          example: Arenicola marina
        commonName:
          type: string
          example: lugworm
        specimenId:
          type: string
          example: SAN000100
        biosampleId:
          type: string
          example: SAMEA12345678
        lifestage:
          type: string
          example: ADULT
        sex:
          type: string
          example: FEMALE
        organismPart:
          type: string
          example: MUSCLE
        GAL:
          type: string
          example: SANGER INSTITUTE
        GALSampleId:
          type: string
          example: SAN000100
        collectedBy:
          type: string
          example: ALEX COLLECTOR
        collectorAffiliation:
          type: string
          example: THE COLLECTOR INSTITUTE
        dateOfCollection:
          type: string
          example: 2020-09-01
        collectionLocation:
          type: string
          example: UK | DARK FOREST
        decimalLatitude:
          type: string
          example: +50.12345678
        decimalLongitude:
          type: string
          example: -1.98765432
        habitat:
          type: string
          example: Woodland
        identifiedBy:
          type: string
          example: JO IDENTIFIER
        identifierAffiliation:
          type: string
          example: THE IDENTIFIER INSTITUTE
        voucherId:
          type: string
          example: voucher1
        tolId:
          type: string
          example: wuAreMari1
      example:
        sampleId: sample1
        taxonomyId: 6344
        scientificName: Arenicola marina
        commonName: lugworm
        specimenId: SAN000100
        biosampleId: SAMEA12345678
        lifestage: ADULT
        sex: FEMALE
        organismPart: MUSCLE
        GAL: SANGER INSTITUTE
        GALSampleId: SAN000100
        collectedBy: ALEX COLLECTOR
        collectorAffiliation: THE COLLECTOR INSTITUTE
        dateOfCollection: 2020-09-01
        collectionLocation: UK | DARK FOREST
        decimalLatitude: +50.12345678
        decimalLongitude: -1.98765432
        habitat: Woodland
        identifiedBy: JO IDENTIFIER
        identifierAffiliation: THE IDENTIFIER INSTITUTE
        voucherId: voucher1
        tolId: wuAreMari1
    User:
      required:
        - name
        - email
        - organisation
        - roles
      type: object
      properties:
        name:
          type: string
          example: "A User"
        email:
          type: string
          example: "user@example.com"
        organisation:
          type: string
          example: "Research Inc"
        roles:
          type: array
          items:
            $ref: '#/components/schemas/Role'
      example:
        name: "A User"
        email: "user@example.com"
        organisation: "Research Inc"
        roles:
    Role:
      required:
        - role
      type: object
      properties:
        role:
          type: string
          example: "creator"
      example:
        role: "creator"
    ErrorMessageList:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorMessage'
    ErrorMessage:
      required:
        - message
      type: object
      properties:
        message:
          type: string
          example: "Something has gone wrong"
      example:
        message: "Something has gone wrong"
  securitySchemes:
    ApiKeyAuth:        # name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: api-key    # name of the header, query parameter or cookie
      x-apikeyInfoFunc: swagger_server.controllers.auth_controller.apikey_auth
# security:
#   - ApiKeyAuth: []     # 2) Apply the API key globally to all operations
  